print("Hello World!")
print("Group 5 Members:")
print("Justin Reyes - The POGI")
print("Juneiah Paredes - jowa ni donny")
print("Calvin Manaor - Pinaka mabait")
print("Nash Wynsjohn Bautista - The one and only.")
